Add configuration options and min/max capabilities
fniephaus/alfred-brightness pull request #3
Opened 2018-08-20 18:57 UTC by squatto

This adds configuration options for:

* "min" option value, and the keyword to trigger it
* "max" option value, and the keyword to trigger it
* Show "min" option?
* Show "max" option?
* Customizable brightness levels, instead of the default 0-100/20

All configuration defaults to what the workflow was already doing (no min/max, levels at 0-100/20). The configuration is done through workflow variables.

2018-08-22 11:16 UTC, fniephaus requested changes
Thanks for PR, happy to integrate it after you refactored the option parsing part a bit :)

2018-08-22 11:16 UTC, fniephaus commented on src/brightness.py
> +brightness_levels = '0,20,40,60,80,100'.split(',')
This could be `brightness_levels = [0, 20, 40, 60, 80, 100]`.

2018-08-22 11:16 UTC, fniephaus commented on src/brightness.py
> +    show_min = os.environ['show_min']
This and other options could be defined simpler, e.g. `show_min = os.environ.get('show_min') == 'true'`.

2018-08-22 11:16 UTC, fniephaus commented on src/brightness.py
> +    brightness_levels = os.environ['brightness_levels'].split(',')
Maybe link this:
```python
brightness_levels = [int(x) for x in os.environ.get('brightness_levels', '0,20,40,60,80,100').split(',')]
```

2018-08-22 23:49 UTC, squatto commented
Wonderful, thank you! I refactored the way they are retrieved and set (Python isn't my native language, so I wasn't aware of .get(key, default) on dictionaries!) I consolidated everything into the initial variable initialization block. Let me know if you see anything else that needs to be changed!

2018-08-24 11:41 UTC, fniephaus requested changes
Thanks a lot for the changes! No problem at all that you aren't "fluent" in Python yet, great you're working on it though :) I left you a few more comments...

2018-08-24 11:41 UTC, fniephaus commented on src/brightness.py
> +    if show_min == 'true':
`if show_min == 'true':` has to read `if show_min:` now :)

2018-08-24 11:41 UTC, fniephaus commented on src/brightness.py
> +    if show_max == 'true':
same...

2018-08-24 11:41 UTC, fniephaus commented on src/brightness.py
> +        error += (', or ' if show_min == 'true' else ' or ') + '"%s"' % keyword_max
It's quite hard to understand what's going on with `error`. I'd prefer something simpler this:

```python
error = 'Enter value between 0 and 100'
if show_min:
    error += ' or %s' % keyword_min
if show_max:
    error += ' or %s' % keyword_max
```
if that makes sense :)

2018-08-24 11:41 UTC, fniephaus commented on src/brightness.py
> +    if show_min == 'true':
`if show_min:`

2018-08-24 11:41 UTC, fniephaus commented on src/brightness.py
> +    if show_max == 'true':
`if show_max:`

2018-08-24 11:41 UTC, fniephaus commented on src/brightness.py
> +        if i.isdigit():
those `i`s should all be ints now :)

2018-08-24 11:41 UTC, fniephaus commented on src/brightness.py
> +            wf.add_item('%s%%' % i, arg='%s' % (int(i) / 100.0), valid=True)
same

2018-08-24 11:41 UTC, fniephaus commented on src/brightness.py
> +brightness_levels = [int(x) for x in os.environ.get('brightness_levels', '0,20,40,60,80,100').split(',')]
```python
brightness_levels_error = None
try:
  brightness_levels = [int(x) for x in os.environ.get('brightness_levels', '0,20,40,60,80,100').split(',')]
except ValueError as e:
  brightness_levels_error = e
```
Then, at the beginning of `main` do:
```python
if brightness_levels_error:  # fail early in case of errors
  wf.add_item(str(brightness_levels_error))
  wf.send_feedback()
  return
```

2018-08-30 16:29 UTC, squatto commented on src/brightness.py
> +        error += (', or ' if show_min == 'true' else ' or ') + '"%s"' % keyword_max
I was going for proper English structure, hence the complexity. haha
I'll simplify it

2018-08-30 16:32 UTC, squatto commented
@fniephaus I made the requested changes 👍🏻 Let me know if you see anything else!

2018-08-30 17:03 UTC, fniephaus approved these changes

2018-08-30 17:31 UTC, fniephaus commented on src/brightness.py
> +        error += (', or ' if show_min == 'true' else ' or ') + '"%s"' % keyword_max
Now that I'm thinking about it, keywords should always be shown in the error message since they always work.

2018-08-30 17:43 UTC, merged

2018-08-30 18:11 UTC, squatto commented
You can disable the min and/or max keywords through the configuration, so that’s why those conditionals are there

2018-08-30 18:12 UTC, squatto commented
Thanks for the merge!

2018-08-30 20:53 UTC, fniephaus commented
> You can disable the min and/or max keywords through the configuration, so that’s why those conditionals are there

Those keywords even work when not displayed, so I'd prefer very simple code for an error message. Have a look at https://github.com/fniephaus/alfred-brightness/commit/7f192c9d3dcf87e92844ac04c7e14f1aaf890d72 and let me know if there's something you don't like.

> Thanks for the merge!

Thanks for the contribution! Your commit is part of [v3.0](https://github.com/fniephaus/alfred-brightness/releases/tag/v3.0).